### ISSUE TITLE
a development document?

### ISSUE THREAD

**Issue by Miracle247** [abau/dilay#22]
I want to contribute to this project as I find it quite fun, could you provide a document for these code files, like the code structure, coding standard as it is a little bit hard for some interested guys like me to grasp the code quickly.

**Comment by abau** [comment]
Thanks for your interest in contributing to Dilay. Unfortunately, I don't have the time to manage any collaborations regarding the development of Dilay (setting up a roadmap, establishing a coding standard, reviewing code, etc.). That's because Dilay is just toy project that I work on in my spare time.

Please don't get me wrong: I really don't mean to be rude. I just don't want people to expect that Dilay is a project that is being worked on continuously and in a professionally manner. It is not. It's just a toy that I like to mess around with.

If you want to contribute to the development of a 3D software, maybe check out [Blender](https://www.blender.org/) or [Wings3D](http://www.wings3d.com/).
