### ISSUE TITLE
Build instructions for Windows?

### ISSUE THREAD

**Issue by jjmac** [abau/dilay#23]
I am unable to build on Windows (using Windows 10, VS2015, and Qt 5.7.0) - are there any specific build instructions?

when building with "nmake release", I get

Command line error D8021 : invalid numeric argument '/Wno-unused-parameter'

**Comment by fenollp** [comment]
Might as well configure AppVeyor

**Comment by abau** [comment]
Never built with VisualStudio because the last time I checked it did not support all C++11/14 features required for building Dilay (this probably changed in the meantime). Thus, all Windows versions of Dilay were built using the Qt Creator along with the Windows port of Mingw. Drawback: no 64 bit builts.

```
Command line error D8021 : invalid numeric argument '/Wno-unused-parameter'
```

Try replacing
```
QMAKE_CXXFLAGS_RELEASE += -DNDEBUG -Wno-unused-parameter -Wno-unused-variable -Wno-maybe-uninitialized
```
in [dilay/common.pri](https://github.com/abau/dilay/blob/2b4041eef52578d6de8a45cf8d6d8994ff917fda/common.pri#L7) by
```
QMAKE_CXXFLAGS_RELEASE += -DNDEBUG
```

For the next release, I'll try building with VS and provide building instructions for Windows.

**Comment by jjmac** [comment]
Thanks for the help, I got it *mostly* to build using your suggestions and also adding #includes for <functional> (in index-octree.hpp) and <string> (in time-delta.cpp and winged/util.cpp) , and also modifying the caseOf template in variant.hpp to return 
    return this->ts.template caseOf<U> (i-1, branches ...);
The only problem now is that I get the error "LINK : fatal error LNK1181: cannot open input file 'obj\src\main.obj'"
So, qmake is not compiling the app project but at this point I don't know why. I'll keep poking at it and if I figure anything out I'll let you know

**Comment by Buzzroid** [comment]
I was able to build almost with MSVC2015, except (hopefully) the last error:

Error   C2059   syntax error: 'template'    dilay   d:\3d-projects\sculpt-projects\dilay\lib\src\variant.hpp    238 

Any help on this error?
