### ISSUE TITLE
Configurable polycount for exports

### ISSUE THREAD

**Issue by SkaveRat** [abau/dilay#3]
Currently the save/export of .obj files seem to have relatively low polygon count. (At least it looks like it, when imported into Blender)

It would be nice to set a polygon count during export or editing of a model, to allow for smoother sculptures (nice for 3d printing)

**Comment by abau** [comment]
Saving a file as .obj file saves all faces of the model. You can verify that by comparing the *Faces* counter in Blender with the same counter in Dilay (displayed in the lower right corner of the screen).

Maybe it just appears as there would be less faces after importing the mesh in Blender because by default Blender renders meshes using flat shading whereas Dilay renders meshes using Smooth shading.
