### ISSUE TITLE
Consider resolving glm dependency via git submodule

### ISSUE THREAD

**Issue by abau** [abau/dilay#42]

**Comment by abau** [comment]
I just learned that git submodules come with their own set of problems. Thus I decided to port Dilay to glm-0.9.5 which is shipped even on Debian 8 and Ubuntu 14.04. Compiling with newer versions of glm still works fine.

**Comment by probonopd** [comment]
Thank you, builds well now but is not installable: https://github.com/abau/dilay/issues/43

**Comment by iKlsR** [comment]
@abau What exactly was the deterrent here?

**Comment by abau** [comment]
@iKlsR I read [this](https://github.com/blog/2104-working-with-submodules) article and the _Advice on using submodules (or not)_ section made me think that the very small changes required to support glm-0.9.5 don't justify importing glm as a submodule.

**Comment by iKlsR** [comment]
Heh, unless you are doing git-fu on a regular, filter/bisect etc shouldn't be a problem really. We've been using them with great success in Blender over the years but I can agree somewhat, it's a pretty small dep to have an extra install step and potential issues with. I've gone and done this to ease building on windows on my end however since I'll be following this project and I don't want a global glm. Cheers.
